# IMPORTING SOME LIBARIES TO USE

In [4]:
import pandas as pd 
import numpy as np 
import matplotlib as plt 


# READING DATASET & SPLIT IT TO FEATURES(X),TARGET(Y)

In [5]:
data = pd.read_csv ("E:\\my prjoects\\machine project\\Heart_Disease_Prediction.csv")
X = data.iloc[ : ,  : -1 ].values 
y = data.iloc[ : , -1  ].values

# DATA PREPROCESSING

In [6]:
# DATA ENCODING
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
y = lb.fit_transform(y)
print (y)

[1 0 1 0 0 0 1 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 1
 1 0 0 1 0 0 0 1 0 1 1 1 1 1 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 0 1 0 1 1 0 0 0
 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 1 1 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 1
 0 1 0 0 0 1 1 0 1 1 1 1 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 0 0 1 0 1 0 1 1 1 1
 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 0 0 1 0 1 1 0 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 1
 0 1 0 0 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0 1 1 0 1 1 1 0 1 0 0 0 0 1 1
 0 0 1 1 0 1 0 0 0 0 1]


In [7]:
# DATA SPLIITING TO TRAIN & TEST
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=1)
print (X_train.shape)
print (y_train.shape)

(216, 13)
(216,)


In [8]:
# FEATURE SCALING(VISUALIZATION)
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# START TO TRAIN OUR MODEL ON SOME ALGORITHMS

In [9]:
# LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
log=LogisticRegression(random_state=1)
log.fit(X_train,y_train)

LogisticRegression(random_state=1)

In [10]:
# SHOW PREDICTION & ACCURACY SCORE & CONFUSION MATRIX
y_pred = log.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
print (accuracy_score(y_test, y_pred))
print (confusion_matrix(y_test, y_pred))

0.8333333333333334
[[28  3]
 [ 6 17]]


In [11]:
# RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
rclassifier = RandomForestClassifier(n_estimators = 8, criterion = 'entropy', random_state = 1)
rclassifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=8, random_state=1)

In [12]:
# SHOW PREDICTION & ACCURACY SCORE & CONFUSION MATRIX
y_pred = rclassifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
print (accuracy_score(y_test, y_pred))
print (confusion_matrix(y_test, y_pred))

0.7407407407407407
[[25  6]
 [ 8 15]]


In [13]:
# NAIVE BAYES
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)

GaussianNB()

In [14]:
# SHOW PREDICTION & ACCURACY SCORE & CONFUSION MATRIX
y_pred = nvclassifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
print (accuracy_score(y_test, y_pred))
print (confusion_matrix(y_test, y_pred))

0.8703703703703703
[[28  3]
 [ 4 19]]


In [15]:
# K-NEAREST NEIGHBORS
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors= 11,weights ='uniform',algorithm ='auto')
KNN.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=11)

In [16]:
# SHOW PREDICTION & ACCURACY SCORE & CONFUSION MATRIX
y_pred = KNN.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
print (accuracy_score(y_test, y_pred))
print (confusion_matrix(y_test, y_pred))

0.8148148148148148
[[26  5]
 [ 5 18]]


In [17]:
# DECISION TREE
from sklearn.tree import DecisionTreeClassifier
dclassifier = DecisionTreeClassifier(criterion = 'entropy')
dclassifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [18]:
# SHOW PREDICTION & ACCURACY SCORE & CONFUSION MATRIX
y_pred = dclassifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
print (accuracy_score(y_test, y_pred))
print (confusion_matrix(y_test, y_pred))

0.6851851851851852
[[20 11]
 [ 6 17]]
